# Initially borrowed from here:  https://gist.github.com/dan-blanchard/7045057
# The validity of this file can be checked here: http://lint.travis-ci.org/

language: python
sudo: false

env:
  global:
    # h5py on Ubuntu, see https://github.com/h5py/h5py/pull/707
    - HDF5_DIR=/usr/lib/x86_64-linux-gnu/hdf5/serial/

matrix:
  include:
    - os: linux
      python: "2.7"
    - os: linux
      python: "3.4"
    - os: linux
      python: "3.5"
    - os: osx
      language: cpp
      env: TRAVIS_PYTHON_VERSION=2.7

# Install packages
install:
  - pip install -r requirements.txt
  - python setup.py install
  - pip install pyflakes pep8

before_script :
  # static code analysis
  #   pyflakes: mainly warnings, unused code, etc.
  - python -m pyflakes .
  #   pep8: style only, enforce PEP 8
  - python -m pep8 --ignore=E201,E202,E122,E127,E128,E131 .

script: 
  - python setup.py test
